# Generated by Django 4.1.7 on 2023-03-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasuremapapi', '0002_image_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='photo_url',
        ),
    ]
